
## Causality diagram
At this point, I started thinking seriously about the causal relationships, based on [this really eye-opening stats lecture](https://www.youtube.com/watch?v=l_7yIUqWBmE). Basically I think you/we shouldn't just "control for body size (or activity)" - what we have is mediator variables, not confounding variables. I think based on this "DAG" (directed acyclic graph, aka path diagram), we need to use something like path analysis, or it's bigger sibling, SEM (structural equation modelling).

The for-loop code at the bottom was found online. It shows that the key things we want to measure (e.g. the effect of selection on respiration, either via body size, activity, or neither) are in fact measureable, which is good (sometimes variables cannot be de-confounded, but in this case we seem to be fine).

```{r}
dag <- dagify(
  VO2 ~ respiration,
  VCO2 ~ respiration,
  respiration ~ body_weight + activity_level + other_traits,
  body_weight ~ selection + sex,
  activity_level ~ selection + sex + cycle,
  other_traits ~ selection + sex + cycle,
  exposure = "selection",
  outcome = "respiration")
ggdag_parents(dag, "respiration")

# List of variable pairs that are (conditionally) independent
# (impliedConditionalIndependencies(dag))

for( n in names(dag) ){
  for( m in children(dag,n) ){
    a <- adjustmentSets(dag, n, m, effect = "direct")
    if( length(a) > 0 ){
      cat("The coefficient on ", n, "->", m,
          " is identifiable controlling for:\n", sep= "")
      print(a, prefix = " * ")
    }
  }
}

```


## Running the structural equation model

This uses the `lavaan` package, which has good documentation. I define a "latent variable" called respiration, which is "measured by" (written with the `=~` operator) VO2 and VCO2. Respiration is affected by body weight, activity, selection treatment, and sex. Also, sex and selection treatment affect body size and activity, such that body size and activity are "mediator variables" in the paths selection->respiration and sex->respiration.

In the "Derived quantities" section of my code, you can see I ask `lavaan` to calculate extra things from its estimate of each path coefficient. For example, I get an estimate of the path from selection treatment via activity to respiration. This is an easy way of getting the correct standard errors for those composite paths (doing it manually, you'd need to use something called the Delta method, which is tricky).
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        Note that I also get an estimate of what I have called RQ from the same model as VO2 and VCO2. The extent to which VO2 and VCO2 measure the same latent variable, "respiration", is basically RQ, I think. The path labelled 0.73. I think this number means that if we define VO2 as being correlated 1-to-1 with respiration (as the model did by default), then VCO2 is correlated withat them both with a regression slope of 0.73. This means that if you consume one unit of oxygen, you produce 0.73 units of CO2, on average. We can also use the model to examine the effect of the 4 upstream variables (weight, activity, selection, sex) on RQ.
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        Shortcoming of the current draft model: I deal with the pseudo-replication by simply throwing away the data from cycles II and III - it is extremely correlated with cycle I, but this is still a sub-optimal choice. I could fix this, but I think it will require going Bayesian, which would stop me getting this back to you quickly. I also ignore the 4 replicate lines, so the model "thinks" that you have more than 4 selection replicates, and thus gives inflated p-values and shrunken standard errors. So, the results will get less significant if/when we control for that in the model.
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        ```{r}
                                                                                                                                                                                                                                                                                                                                        model <- ' 
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        # latent variable definitions 
                                                                                                                                                                                                                                                                                                                                        respiration =~ VO2 + E*VCO2
                                                                                                                                                                                                                                                                                                                                        #   VCO2 ~~ VO2
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        respiration ~ v*MALE + x*BODY_WEIGHT + y*ACTIVITY + z*POLYANDRY
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        BODY_WEIGHT ~ a*POLYANDRY + c*MALE
                                                                                                                                                                                                                                                                                                                                        ACTIVITY ~ b*POLYANDRY + d*MALE
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        # Derived quantities:
                                                                                                                                                                                                                                                                                                                                        RQ := E
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        body_RQ := E*x
                                                                                                                                                                                                                                                                                                                                        activity_RQ := E*y
                                                                                                                                                                                                                                                                                                                                        remainder_RQ := E*z
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        sel_body_RQ := a*x*E
                                                                                                                                                                                                                                                                                                                                        sel_activity_RQ := b*y*E
                                                                                                                                                                                                                                                                                                                                        sel_remainder_RQ := z*E
                                                                                                                                                                                                                                                                                                                                        total_sel_RQ := z*E + (a*x*E) + (b*y*E)
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        sex_body_RQ := c*x*E
                                                                                                                                                                                                                                                                                                                                        sex_activity_RQ := d*y*E
                                                                                                                                                                                                                                                                                                                                        sex_remainder_RQ := v*E
                                                                                                                                                                                                                                                                                                                                        total_sex_RQ := v*E + (c*x*E) + (d*y*E)
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        sel_body_resp := a*x
                                                                                                                                                                                                                                                                                                                                        sel_activity_resp := b*y
                                                                                                                                                                                                                                                                                                                                        sel_remainder_resp := z
                                                                                                                                                                                                                                                                                                                                        total_sel_resp := z + (a*x) + (b*y)
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        sex_body_resp := c*x
                                                                                                                                                                                                                                                                                                                                        sex_activity_resp := d*y
                                                                                                                                                                                                                                                                                                                                        sex_remainder_resp := v
                                                                                                                                                                                                                                                                                                                                        total_sex_resp := v + (c*x) + (d*y)
                                                                                                                                                                                                                                                                                                                                        '
                                                                                                                                                                                                                                                                                                                                        scaled_data <- respiration %>%
                                                                                                                                                                                                                                                                                                                                        mutate(VO2 = VO2*1000,
                                                                                                                                                                                                                                                                                                                                        VCO2 = VCO2*1000,
                                                                                                                                                                                                                                                                                                                                        BODY_WEIGHT = as.numeric(scale(BODY_WEIGHT)),
                                                                                                                                                                                                                                                                                                                                        ACTIVITY = as.numeric(scale(ACTIVITY)),
                                                                                                                                                                                                                                                                                                                                        POLYANDRY = ifelse(SELECTION == "Mono", 0, 1),
                                                                                                                                                                                                                                                                                                                                        MALE = ifelse(SEX == "F", 0, 1))
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        fit <- sem(model, data = scaled_data %>% filter(CYCLE == "I"))
                                                                                                                                                                                                                                                                                                                                        ```
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        ### Estimates from the model
                                                                                                                                                                                                                                                                                                                                        Basically, selection does affect respiration and it's highly significant, but it does it by increasing activity level. There is no evidence that polyandrous flies respire more "pound for pound", or that they respure more for any given activity level.
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        Similarly, selection has a weakly significant effect on RQ (i.e. polyandry flies burn a greater amount of sugar vs lipid). However, this is mostly because polyandry flies are more active than monogamy flies.
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        Interestingly, male flies respire more even after controlling for the sex differences in body weight and activity level. 
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        ```{r}
                                                                                                                                                                                                                                                                                                                                        summary(fit, fit.measures = TRUE)
                                                                                                                                                                                                                                                                                                                                        # parameterEstimates(fit) # <- table of these estimates
                                                                                                                                                                                                                                                                                                                                        # See page 2 about how to interpret RMSEA: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.233.3090&rep=rep1&type=pdf
                                                                                                                                                                                                                                                                                                                                        ```
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        ```{r}
                                                                                                                                                                                                                                                                                                                                        lavaanPlot (model=fit, coefs=T, stars="regress")
                                                                                                                                                                                                                                                                                                                                        ```
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        